# Generated by Django 5.0.4 on 2024-12-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('master_index', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('before_after', models.CharField(db_index=True, max_length=10)),
                ('date_diff', models.IntegerField(db_index=True)),
                ('flight_length', models.IntegerField(db_index=True)),
                ('label', models.CharField(db_index=True, max_length=255)),
                ('hierarchy', models.CharField(blank=True, max_length=255, null=True)),
                ('number_flights_before', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='monitoring.flight')),
            ],
        ),
    ]
